import{i as c,S as m,a as f}from"./assets/vendor-c493984e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const y=document.querySelector(".gallery");y.style.display="grid";y.style.gridTemplateColumns="repeat(auto-fill, minmax(300px, 1fr))";y.style.gap="16px";y.style.padding="16px";function g(n){if(!Array.isArray(n)){c.error({title:"Error",message:"displayImages expects an array but received:"+typeof n});return}const s=document.getElementById("imageResults");s.innerHTML="",n.forEach(r=>{const e=document.createElement("a");e.classList.add("image-card"),e.href=r.largeImageURL,e.innerHTML=`
            
            <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
            
            <div class="info">
                <p><b>Likes:</b> ${r.likes}</p>
                <p><b>Views:</b> ${r.views}</p>
                <p><b>Comments:</b> ${r.comments}</p>
                <p><b>Downloads:</b> ${r.downloads}</p>
            </div>`,s.appendChild(e);const t=e;t.style.position="relative",t.style.overflow="hidden",t.style.borderRadius="8px",t.style.boxShadow="0 2px 8px rgba(0, 0, 0, 0.1)";const o=e.querySelector(".info");o.style.position="absolute",o.style.bottom="0",o.style.left="0",o.style.right="0",o.style.padding="8px",o.style.background="rgba(0, 0, 0, 0.6)",o.style.color="#fff",o.style.fontSize="14px"}),new m(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function h(){const n=document.getElementById("imageResults");n.innerHTML=""}async function b(n,s){const i="https://pixabay.com/",r="api/",e=new URLSearchParams({key:n,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),t=`${i}${r}?${e}`;x();try{const u=(await f.get(t)).data;u.hits.length===0?(h(),c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})):g(u.hits)}catch{c.error({title:"Error",message:"An error occurred while fetching images. Please try again!"})}finally{L()}}const p=document.querySelector(".loader");function x(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const w="44406774-b6929e0ee65f9835201f12742",a=document.querySelector("form");a.style.display="flex";a.style.justifyContent="center";a.style.gap="8px";a.style.height="40px";a.style.width="371px";a.style.margin="0 auto";a.style.fontFamily="Montserrat";a.style.fontSize="16px";const d=document.querySelector("input");d.style.width="272px";d.style.paddingLeft="16px";d.style.border="1px solid #808080";d.style.borderRadius="4px";d.style.color="#808080";const l=document.querySelector("button");l.style.width="91px";l.style.padding="0px";l.style.backgroundColor="#4E75FF";l.style.border="none";l.style.borderRadius="8px";l.style.color="#FFFFFF";document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector("form"),s=document.querySelector('input[type="text"]');n.addEventListener("submit",async i=>{if(i.preventDefault(),s.value.trim()==="")c.error({title:"Error",message:"Поле пошуку не може бути порожнім"});else try{await b(w,s.value),s.value=""}catch(r){c.error({title:"Error",message:"An error occurred while fetching images. Please try again!"}),console.error("Error fetching images:",r)}})});
//# sourceMappingURL=commonHelpers.js.map
